[package]
name = "mtx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
term_size = "0.3"
console = "0.15.8"
array2d = "0.3.2"
